kind = "DojoModel"
class_hash = "0x65ad8394aad8d83cbdbbcce8d3dda2ed3b8d5f4b3e16b872d22d092d8cdb09f"
original_class_hash = "0x65ad8394aad8d83cbdbbcce8d3dda2ed3b8d5f4b3e16b872d22d092d8cdb09f"
abi = "manifests/dev/abis/base/models/boot_camp_paint_models_tile_tile.json"
name = "boot_camp_paint::models::tile::tile"

[[members]]
name = "x"
type = "u16"
key = true

[[members]]
name = "y"
type = "u16"
key = true

[[members]]
name = "player_address"
type = "starknet::ContractAddress"
key = true

[[members]]
name = "color"
type = "felt252"
key = false
