kind = "DojoModel"
class_hash = "0x5dbe53ecba433797af7d3aff2c42de379ffa1473a1af2ff0d8439ac80ffedfb"
original_class_hash = "0x5dbe53ecba433797af7d3aff2c42de379ffa1473a1af2ff0d8439ac80ffedfb"
abi = "manifests/dev/abis/base/models/dojo_starter_models_game_game.json"
name = "dojo_starter::models::game::game"

[[members]]
name = "game_id"
type = "u32"
key = true

[[members]]
name = "player_1"
type = "ContractAddress"
key = false

[[members]]
name = "player_2"
type = "ContractAddress"
key = false

[[members]]
name = "state"
type = "GameState"
key = false
