kind = "DojoModel"
class_hash = "0x418b5c3fa70cec3e35a02db05d82f94b3211dc4b0c5004510ecf89c24a5b611"
original_class_hash = "0x418b5c3fa70cec3e35a02db05d82f94b3211dc4b0c5004510ecf89c24a5b611"
abi = "manifests/dev/abis/base/models/dojo_starter_models_player_player.json"
name = "dojo_starter::models::player::player"

[[members]]
name = "address"
type = "ContractAddress"
key = true

[[members]]
name = "name"
type = "felt252"
key = false

[[members]]
name = "game_id"
type = "u32"
key = false
