// Generated by dojo-bindgen on Sat, 22 Jun 2024 21:08:40 +0000. Do not modify this file manually.
import { Account } from "starknet";
import {
    Clause,
    Client,
    ModelClause,
    createClient,
    valueToToriiValueAndOperator,
} from "@dojoengine/torii-client";
import {
    LOCAL_KATANA,
    LOCAL_RELAY,
    LOCAL_TORII,
    createManifestFromJson,
} from "@dojoengine/core";

// Type definition for `core::byte_array::ByteArray` struct
export interface ByteArray {
    data: string[];
    pending_word: string;
    pending_word_len: number;
}

// Type definition for `dojo_starter::models::player::Player` struct
export interface Player {
    address: string;
    name: string;
    game_id: number;
}

// Type definition for `core::option::Option::<core::integer::u32>` enum
type Option<A> = { type: 'Some'; data: A; } | { type: 'None'; }

// Type definition for `dojo_starter::models::game::Game` struct
export interface Game {
    game_id: number;
    player_1: string;
    player_2: string;
    state: GameState;
}

// Type definition for `dojo_starter::models::game::GameState` enum
type GameState = { type: 'Waiting'; } | { type: 'Locked'; } | { type: 'Running'; } | { type: 'Done'; }

// Type definition for `dojo_starter::models::position::Vec2` struct
export interface Vec2 {
    x: number;
    y: number;
}

// Type definition for `dojo_starter::models::position::Position` struct
export interface Position {
    player: string;
    vec: Vec2;
}


// Type definition for `dojo_starter::models::queue::Queue` struct
export interface Queue {
    queue_id: string;
    player: string;
}


// Type definition for `dojo_starter::models::moves::DirectionsAvailable` struct
export interface DirectionsAvailable {
    player: string;
    directions: Direction[];
}

// Type definition for `dojo_starter::models::moves::Direction` enum
type Direction = { type: 'None'; } | { type: 'Left'; } | { type: 'Right'; } | { type: 'Up'; } | { type: 'Down'; }

// Type definition for `dojo_starter::systems::actions::actions::Moved` struct
export interface Moved {
    player: string;
    direction: Direction;
}


// Type definition for `dojo_starter::models::moves::Moves` struct
export interface Moves {
    player: string;
    remaining: number;
    last_direction: Direction;
    can_move: boolean;
}


class BaseCalls {
    contractAddress: string;
    account?: Account;

    constructor(contractAddress: string, account?: Account) {
        this.account = account;
        this.contractAddress = contractAddress;
    }

    async execute(entrypoint: string, calldata: any[] = []): Promise<void> {
        if (!this.account) {
            throw new Error("No account set to interact with dojo_starter");
        }

        await this.account.execute(
            {
                contractAddress: this.contractAddress,
                entrypoint,
                calldata,
            },
            undefined,
            {
                maxFee: 0,
            }
        );
    }
}

class ActionsCalls extends BaseCalls {
    constructor(contractAddress: string, account?: Account) {
        super(contractAddress, account);
    }

    async spawn(): Promise<void> {
        try {
            await this.execute("spawn", [])
        } catch (error) {
            console.error("Error executing spawn:", error);
            throw error;
        }
    }

    async move(direction: Direction): Promise<void> {
        try {
            await this.execute("move", [direction])
        } catch (error) {
            console.error("Error executing move:", error);
            throw error;
        }
    }

    async dojoResource(): Promise<void> {
        try {
            await this.execute("dojo_resource", [])
        } catch (error) {
            console.error("Error executing dojoResource:", error);
            throw error;
        }
    }

    async dojoInit(): Promise<void> {
        try {
            await this.execute("dojo_init", [])
        } catch (error) {
            console.error("Error executing dojoInit:", error);
            throw error;
        }
    }
}
class PrivateRoomCalls extends BaseCalls {
    constructor(contractAddress: string, account?: Account) {
        super(contractAddress, account);
    }

    async dojoInit(): Promise<void> {
        try {
            await this.execute("dojo_init", [])
        } catch (error) {
            console.error("Error executing dojoInit:", error);
            throw error;
        }
    }

    async dojoResource(): Promise<void> {
        try {
            await this.execute("dojo_resource", [])
        } catch (error) {
            console.error("Error executing dojoResource:", error);
            throw error;
        }
    }

    async leave(game_id: number): Promise<void> {
        try {
            await this.execute("leave", [game_id])
        } catch (error) {
            console.error("Error executing leave:", error);
            throw error;
        }
    }

    async join(game_id: number): Promise<void> {
        try {
            await this.execute("join", [game_id])
        } catch (error) {
            console.error("Error executing join:", error);
            throw error;
        }
    }

    async createPlayer(): Promise<void> {
        try {
            await this.execute("create_player", [])
        } catch (error) {
            console.error("Error executing createPlayer:", error);
            throw error;
        }
    }

    async createGame(): Promise<void> {
        try {
            await this.execute("create_game", [])
        } catch (error) {
            console.error("Error executing createGame:", error);
            throw error;
        }
    }
}
class PublicRoomCalls extends BaseCalls {
    constructor(contractAddress: string, account?: Account) {
        super(contractAddress, account);
    }

    async dojoResource(): Promise<void> {
        try {
            await this.execute("dojo_resource", [])
        } catch (error) {
            console.error("Error executing dojoResource:", error);
            throw error;
        }
    }

    async dojoInit(): Promise<void> {
        try {
            await this.execute("dojo_init", [])
        } catch (error) {
            console.error("Error executing dojoInit:", error);
            throw error;
        }
    }

    async register(name: string): Promise<void> {
        try {
            await this.execute("register", [name])
        } catch (error) {
            console.error("Error executing register:", error);
            throw error;
        }
    }

    async unregister(): Promise<void> {
        try {
            await this.execute("unregister", [])
        } catch (error) {
            console.error("Error executing unregister:", error);
            throw error;
        }
    }
}

type Query = Partial<{
    Player: ModelClause<Player>;
    Game: ModelClause<Game>;
    Position: ModelClause<Position>;
    Queue: ModelClause<Queue>;
    DirectionsAvailable: ModelClause<DirectionsAvailable>;
    Moved: ModelClause<Moved>;
    Moves: ModelClause<Moves>;
}>;

type ResultMapping = {
    Player: Player;
    Game: Game;
    Position: Position;
    Queue: Queue;
    DirectionsAvailable: DirectionsAvailable;
    Moved: Moved;
    Moves: Moves;
};

type QueryResult<T extends Query> = {
    [K in keyof T]: K extends keyof ResultMapping ? ResultMapping[K] : never;
};

// Only supports a single model for now, since torii doesn't support multiple models
// And inside that single model, there's only support for a single query.
function convertQueryToToriiClause(query: Query): Clause | undefined {
    const [model, clause] = Object.entries(query)[0];

    if (Object.keys(clause).length === 0) {
        return undefined;
    }

    const clauses: Clause[] = Object.entries(clause).map(([key, value]) => {
        return {
            Member: {
                model,
                member: key,
                ...valueToToriiValueAndOperator(value),
            },
        } satisfies Clause;
    });

    return clauses[0];
}
type GeneralParams = {
    toriiUrl?: string;
    relayUrl?: string;
    account?: Account;
};

type InitialParams = GeneralParams &
    (
        | {
                rpcUrl?: string;
                worldAddress: string;
                actionsAddress: string;
    privateRoomAddress: string;
    publicRoomAddress: string;
            }
        | {
                manifest: any;
            }
    );

export class DojoStarter {
    rpcUrl: string;
    toriiUrl: string;
    toriiPromise: Promise<Client>;
    relayUrl: string;
    worldAddress: string;
    private _account?: Account;
    actions: ActionsCalls;
    actionsAddress: string;
    privateRoom: PrivateRoomCalls;
    privateRoomAddress: string;
    publicRoom: PublicRoomCalls;
    publicRoomAddress: string;

    constructor(params: InitialParams) {
        if ("manifest" in params) {
            const config = createManifestFromJson(params.manifest);
            this.rpcUrl = config.world.metadata.rpc_url;
            this.worldAddress = config.world.address;

            const actionsAddress = config.contracts.find(
                (contract) =>
                    contract.name === "dojo_starter::systems::actions::actions"
            )?.address;

            if (!actionsAddress) {
                throw new Error("No actions contract found in the manifest");
            }

            this.actionsAddress = actionsAddress;
    const privateRoomAddress = config.contracts.find(
                (contract) =>
                    contract.name === "dojo_starter::systems::privateRoom::privateRoom"
            )?.address;

            if (!privateRoomAddress) {
                throw new Error("No privateRoom contract found in the manifest");
            }

            this.privateRoomAddress = privateRoomAddress;
    const publicRoomAddress = config.contracts.find(
                (contract) =>
                    contract.name === "dojo_starter::systems::publicRoom::publicRoom"
            )?.address;

            if (!publicRoomAddress) {
                throw new Error("No publicRoom contract found in the manifest");
            }

            this.publicRoomAddress = publicRoomAddress;
        } else {
            this.rpcUrl = params.rpcUrl || LOCAL_KATANA;
            this.worldAddress = params.worldAddress;
            this.actionsAddress = params.actionsAddress;
    this.privateRoomAddress = params.privateRoomAddress;
    this.publicRoomAddress = params.publicRoomAddress;
        }
        this.toriiUrl = params.toriiUrl || LOCAL_TORII;
        this.relayUrl = params.relayUrl || LOCAL_RELAY;
        this._account = params.account;
        this.actions = new ActionsCalls(this.actionsAddress, this._account);
    this.privateRoom = new PrivateRoomCalls(this.privateRoomAddress, this._account);
    this.publicRoom = new PublicRoomCalls(this.publicRoomAddress, this._account);

        this.toriiPromise = createClient([], {
            rpcUrl: this.rpcUrl,
            toriiUrl: this.toriiUrl,
            worldAddress: this.worldAddress,
            relayUrl: this.relayUrl,
        });
    }

    get account(): Account | undefined {
        return this._account;
    }

    set account(account: Account) {
        this._account = account;
        this.actions = new ActionsCalls(this.actionsAddress, this._account);
    this.privateRoom = new PrivateRoomCalls(this.privateRoomAddress, this._account);
    this.publicRoom = new PublicRoomCalls(this.publicRoomAddress, this._account);
    }

    async query<T extends Query>(query: T, limit = 10, offset = 0) {
        const torii = await this.toriiPromise;

        return {
            torii,
            findEntities: async () => this.findEntities(query, limit, offset),
        };
    }

    async findEntities<T extends Query>(query: T, limit = 10, offset = 0) {
        const torii = await this.toriiPromise;

        const clause = convertQueryToToriiClause(query);

        const toriiResult = await torii.getEntities({
            limit,
            offset,
            clause,
        });

        return toriiResult as Record<string, QueryResult<T>>;
    }

    async findEntity<T extends Query>(query: T) {
        const result = await this.findEntities(query, 1);

        if (Object.values(result).length === 0) {
            return undefined;
        }

        return Object.values(result)[0] as QueryResult<T>;
    }
}