/* Autogenerated file. Do not edit manually. */

import { defineComponent, Type as RecsType, World } from "@dojoengine/recs";

export type ContractComponents = Awaited<ReturnType<typeof defineContractComponents>>;

export function defineContractComponents(world: World) {
  return {
    Game: (() => {
      return defineComponent(
        world,
        { game_id: RecsType.Number, player_1: RecsType.BigInt, player_2: RecsType.BigInt, state: RecsType.Number },
        {
          metadata: {
            name: "Game",
            types: ["u32","contractaddress","contractaddress","enum"],
            customTypes: ["GameState"],
          },
        }
      );
    })(),
    DirectionsAvailable: (() => {
      return defineComponent(
        world,
        { player: RecsType.BigInt, directions: RecsType.StringArray },
        {
          metadata: {
            name: "DirectionsAvailable",
            types: ["contractaddress"],
            customTypes: [],
          },
        }
      );
    })(),
    Moves: (() => {
      return defineComponent(
        world,
        { player: RecsType.BigInt, remaining: RecsType.Number, last_direction: RecsType.Number, can_move: RecsType.Boolean },
        {
          metadata: {
            name: "Moves",
            types: ["contractaddress","u8","enum","bool"],
            customTypes: ["Direction"],
          },
        }
      );
    })(),
    Player: (() => {
      return defineComponent(
        world,
        { address: RecsType.BigInt, name: RecsType.BigInt, game_id: RecsType.Number },
        {
          metadata: {
            name: "Player",
            types: ["contractaddress","felt252","u32"],
            customTypes: [],
          },
        }
      );
    })(),
    Position: (() => {
      return defineComponent(
        world,
        { player: RecsType.BigInt, vec: { x: RecsType.Number, y: RecsType.Number } },
        {
          metadata: {
            name: "Position",
            types: ["contractaddress","u32","u32"],
            customTypes: ["Vec2"],
          },
        }
      );
    })(),
    Queue: (() => {
      return defineComponent(
        world,
        { queue_id: RecsType.BigInt, player: RecsType.BigInt },
        {
          metadata: {
            name: "Queue",
            types: ["felt252","contractaddress"],
            customTypes: [],
          },
        }
      );
    })(),
    Moved: (() => {
      return defineComponent(
        world,
        { player: RecsType.BigInt, direction: RecsType.Number },
        {
          metadata: {
            name: "Moved",
            types: ["contractaddress","enum"],
            customTypes: ["Direction"],
          },
        }
      );
    })(),
  };
}
